// Generated by scripts/generate-plugin-contract.mjs. Do not edit directly.

export type PluginCapabilityFamily = 'codeblock' | 'text-rendering' | 'llm-tool'
export type PluginDiagnosticCode = 'PLUGIN_INVALID_JSON' | 'PLUGIN_UNKNOWN_SCHEMA_VERSION' | 'PLUGIN_INVALID_MANIFEST' | 'PLUGIN_UNSUPPORTED_CAPABILITY_VERSION' | 'PLUGIN_INCOMPATIBLE_HOST_VERSION' | 'PLUGIN_PATH_ESCAPE' | 'PLUGIN_MISSING_RESOURCE' | 'PLUGIN_DIGEST_MISMATCH' | 'PLUGIN_DUPLICATE_PACKAGE_ID' | 'PLUGIN_DUPLICATE_CAPABILITY_ID' | 'PLUGIN_DUPLICATE_SKILL_ID' | 'PLUGIN_UNKNOWN_RESOURCE_REFERENCE' | 'PLUGIN_PACKAGE_READ_FAILED'
export type PluginDiagnosticSeverity = 'error' | 'warning' | 'info'
export type PluginOrigin = 'bundled'
export type PluginLifecycleStatus = 'ready' | 'invalid' | 'incompatible' | 'failed'
export type PluginResourcePurpose = 'documentation' | 'metadata' | 'skill-instructions'
export type PluginResourceMediaType = 'application/json' | 'text/markdown' | 'text/plain'

export type PluginManifestCompatibility = {
  mdv: {
    minVersion: string
    maxVersionExclusive: string
  }
  pluginApiVersion: number
}

export type PluginManifestResource = {
  id: string
  path: string
  sha256: string
  mediaType: PluginResourceMediaType
  purpose: PluginResourcePurpose
}

export type PluginManifestCapabilityBase = {
  id: string
  contractVersion: number
  permissions: []
  resourceIds: string[]
}

export type PluginCodeblockCapability = PluginManifestCapabilityBase & {
  family: 'codeblock'
  languages: string[]
}

export type PluginTextRenderingCapability = PluginManifestCapabilityBase & {
  family: 'text-rendering'
  formats: ['markdown-text']
}

export type PluginLlmToolCapability = PluginManifestCapabilityBase & {
  family: 'llm-tool'
  toolNames: string[]
}

export type PluginManifestCapability = PluginCodeblockCapability | PluginTextRenderingCapability | PluginLlmToolCapability

export type PluginSkillContribution = {
  id: string
  displayName: string
  version: string
  instructionResourceId: string
  resourceIds: string[]
}

export type PluginManifestFacts = {
  schemaVersion: number
  id: string
  displayName: string
  version: string
  compatibility: PluginManifestCompatibility
  resources: PluginManifestResource[]
  capabilities: PluginManifestCapability[]
  skills: PluginSkillContribution[]
}

export type PluginDiagnosticDefinition = {
  code: PluginDiagnosticCode
  severity: PluginDiagnosticSeverity
  publicMessage: string
  developerDetail: string
  remediation: string
}

export type BundledPluginRegistration = {
  catalogId: string
  manifestPath: string
}

export type PluginCapabilityContract =
  | { family: 'codeblock'; contractVersion: number; payloadField: 'languages'; itemPattern: string }
  | { family: 'text-rendering'; contractVersion: number; payloadField: 'formats'; allowedItems: readonly string[] }
  | { family: 'llm-tool'; contractVersion: number; payloadField: 'toolNames'; itemPattern: string }

export type PluginRuntimeContract = {
  PLUGIN_CONTRACT: {
    contractVersion: number
    manifestSchemaVersion: number
    pluginApiVersion: number
    idPattern: string
    versionPattern: string
    resourcePathPattern: string
    sha256Pattern: string
    limits: {
      manifestBytes: number
      displayNameCharacters: number
      idCharacters: number
      versionCharacters: number
      resources: number
      capabilities: number
      skills: number
      stringListItems: number
    }
    resourcePurposes: readonly PluginResourcePurpose[]
    mediaTypes: readonly PluginResourceMediaType[]
    capabilityFamilies: readonly PluginCapabilityContract[]
  }
  PLUGIN_MANIFEST_SCHEMA: object
  PLUGIN_DIAGNOSTICS: readonly PluginDiagnosticDefinition[]
  BUNDLED_PLUGIN_REGISTRATIONS: readonly BundledPluginRegistration[]
}

export type PluginPublicContribution = {
  id: string
  family: PluginCapabilityFamily | 'skill'
  version: number | string
  availability: 'declared' | 'unavailable'
  executable: false
  loaded: false
}

export type PluginPublicDiagnostic = {
  code: PluginDiagnosticCode
  severity: PluginDiagnosticSeverity
  message: string
}

export type PluginPublicPackageDiagnostics = {
  catalogId: string
  packageId: string | null
  displayName: string | null
  version: string | null
  origin: PluginOrigin
  status: PluginLifecycleStatus
  packageDigestSha256: string | null
  capabilities: PluginPublicContribution[]
  skills: PluginPublicContribution[]
  diagnostics: PluginPublicDiagnostic[]
}

export type PluginPublicCatalogDiagnostics = {
  contractVersion: number
  hostVersion: string
  packages: PluginPublicPackageDiagnostics[]
}
